### ISSUE TITLE
iWit USB Controller Update Request

### ISSUE THREAD

**Issue by androidotai** [M-Reimer/IwitVolumeKnob#1]
Hi M-Reimer,

Sorry for disturbing your repo here. Currently I have one iWit USB Controller. I want to remap all the key function to emulate Surface Dial like someone do. But, I notice no key list for Surface Dial. My iWit USB Controller version is V4.01 and theirs is V4.81 (from this video https://www.youtube.com/watch?v=eR3obDyGL48). Any idea how to update the controller?

**Comment by M-Reimer** [comment]
My idea was never to use the original firmware at all but to completely reprogram the device and making this easy by adding an Arduino bootloader to it. This allows for true reprogramming but also requires a bit more effort to do so.

In theory this also allows to have "surface dial" functionality which, as far as I could find out, is some proprietary device primarily targeting the expensive "Microsoft Surface". If someone wants to do this: Go for it and tell me about your repository so I can link you.

As I'm no Surface user and no Windows user either there is not much use for this proprietary device for me as I would have to run a helper service to map it to useful input events in this case. But as I now have the whole iWit programmable I could also program more useful input events directly into the microcontroller of the iWit device.

Oh, and about "updating the original firmware": I don't think this works at all. My solution actually completely wipes out the original firmware with the bootloader needed to do the software change via USB. But the original firmware is gone in this case and can not be restored. Maybe they missed to set security fuse bits. This could in theory allow to read the firmware from a new device with the new firmware. But I think they did their homework and protected their firmware.
